### ISSUE TITLE
compile error on MacOS Ventura 

### ISSUE THREAD

**Issue by JayStolzenwald** [ros2/performance_test_fixture#23]
I'm getting this when trying to compile on MacOS Ventura 13.2.1 (Intel):

```
stderr: performance_test_fixture                                                                      
Undefined symbols for architecture x86_64:
  "osrf_testing_tools_cpp::memory_tools::on_unexpected_calloc(std::__1::variant<std::__1::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::__1::function<void ()>, std::nullptr_t>)", referenced from:
      performance_test_fixture::PerformanceTest::SetUp(benchmark::State&) in performance_test_fixture.cpp.o
  "osrf_testing_tools_cpp::memory_tools::on_unexpected_malloc(std::__1::variant<std::__1::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::__1::function<void ()>, std::nullptr_t>)", referenced from:
      performance_test_fixture::PerformanceTest::SetUp(benchmark::State&) in performance_test_fixture.cpp.o
  "osrf_testing_tools_cpp::memory_tools::on_unexpected_realloc(std::__1::variant<std::__1::function<void (osrf_testing_tools_cpp::memory_tools::MemoryToolsService&)>, std::__1::function<void ()>, std::nullptr_t>)", referenced from:
      performance_test_fixture::PerformanceTest::SetUp(benchmark::State&) in performance_test_fixture.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libperformance_test_fixture.dylib] Error 1
make[1]: *** [CMakeFiles/performance_test_fixture.dir/all] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 13 jobserver tokens available; should be 12!

Failed   <<< performance_test_fixture [6.82s, exited with code 2]
Aborted ...
```

**Comment by clalancette** [comment]
Just out of curiousity, if you use https://github.com/osrf/osrf_testing_tools_cpp/pull/76 , does that help the situation at all?

**Comment by JayStolzenwald** [comment]
@clalancette , this does not seem to be part of ros2 is it? Not sure how to integrate this

**Comment by clalancette** [comment]
> @clalancette , this does not seem to be part of ros2 is it? Not sure how to integrate this

It is one of the libraries we depend upon and build as part of our build instructions, yes.

**Comment by JayStolzenwald** [comment]
I see this got merged only a few hours ago. Works now, thanks for the quick response, you guys are amazing
